name: build-linux
on: 
  pull_request:
  push:
    tags:
      - '*'
jobs:
  build:
    if: github.event_name == 'pull_request' ||
        (github.event_name == 'push' &&
        startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build Linux executable
      run: |
        sudo apt-get install -y libegl1-mesa
        pip install poetry
        poetry install
        poetry run build
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: linux-release
        path: dist/reflex-nexus
  publish:
    name: Publish release
    needs: build
    if: github.event_name == 'push' &&
        startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: linux-release
      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: linux-release/reflex-nexus
