name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      name: Lint project
    - run: |
        sudo apt-get update
        sudo apt-get install -y libegl1-mesa
        pip install poetry
        poetry install
        poetry run lint
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: lint-report
        path: lint.txt
