name: MacOS Build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Build the executable
      run: poetry run build
    - name: Build the documentation HTML
      run: poetry run docs
    - name: Lint the project
      run: poetry run lint
    - name: Test the project
      run: poetry run test
