name: package
on:
  release:
    types: [ published ]
jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: Upload release to PyPI
      url: https://pypi.org/p/reflex-nexus
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1-mesa
        pip install poetry
        poetry install
    - name: Build package
      run: |
        poetry build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
