name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run test suite
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1-mesa
        pip install poetry
        poetry install
        poetry run test
    - name: Upload to coveralls
      uses: coverallsapp/github-action@v2
    - name: Upload report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report
        path: test.xml
