on:
  push:
    tags:
      - '*'
name: Publish Release
jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: linux-release
      - uses: actions/download-artifact@v2
        with:
          name: macos-release
      - uses: actions/download-artifact@v2
        with:
          name: windows-release
      - name: Create Release and Upload Artifacts
        id: publish_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux-release
            macos-release
            windows-release
