name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry run test
    - uses: AndreMiras/coveralls-python-action@develop
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coveralls-token: ${{ secrets.COVERALLS_TOKEN }}
